motd: "§6       §8§l4WORLD §8[1.8.X] - §fdiscord.gg/44world\n§6         &f    &fNovas expêriencias! &a▍▍▍▍§8▍▍▍▍▍ &a40% "

motd-manu: "§6       §8§l4WORLD §8[1.8.X] - §fdiscord.gg/44world\n§6         &f    &fNovas expêriencias! &a▍▍▍▍§8▍▍▍▍▍ &a40% "